### PR TITLE
fixed package compile for kinetic/xenial

### PR DESCRIPTION
**Pull request by davefeilseifer**
all packages now compile on kinetic/xenial

relies on eml package which is autobuilding in bloom

### CODE REVIEW

**Review by v4hn — APPROVED** [review]
I would really like to get rid of some of these packages and move to `ros_ethercat` and `ros_control`.
But somebody would have to do this...

**Comment by davefeilseifer** [comment]
Michael-

I took a preliminary work at moving to ros_ethercat and ros_control last
month. The underlying structure of the package is somewhat different
requiring some significant development/testing. Once pr2_ethercat_drivers
was being tested on xenial on our PR2 I was going to take a look at moving
those over to the more general packages. However, that's not likely to
happen for at least 2 months, since aside from the PR2, I don't have any
ethercat hardware to test things on and our PR2 is in the critical path for
a bunch of projects. If anyone wants to send me some PR2 ethercat hardware
I can test on, I'd gladly try and move that up.

-Dave

**Comment by v4hn** [comment]
I spent a bit of work on this a few months ago too, because we wanted to integrate a Shadow Hand with the PR2 ethercat system.
But I did not have the resources to finish the implementation and eventually we decided to use a different ethercat loop.
You are right, integrating the PR2 plugins with `ros_ethercat` requires substantial changes.

I'm very happy to hear someone else is interested in and working on modernizing the PR2 modules!
Thank you for your work!

**Comment by k-okada** [comment]
@davefeilseifer @v4hn sorry for late,  I have included this into #75

**Pull request closed without merging**
